/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.24;

interface IRiskOracle  {
    function initialize(address aguayo_sbt_address) external;

    function areAllMembersEligible(address[] memory members) external view returns (bool);

    function getLeverageLevel(address[] memory members) external view returns (uint256, uint256);

    function getWeightedProbabilities(address[] memory members) external view returns (uint256[] memory);

    function isMemberEligible(address member, bool is_credit_mode) external view returns (bool);

    function getLeverageTierCount() external view returns (uint256);

    function getLeverageTier(uint256 tier_id) external view returns (uint8, uint256, uint256);

    function owner() external view returns (address);

    function aguayoSbt() external view returns (address);

    function minLevelForCredit() external view returns (uint8);

    function maxLeverageMultiplier() external view returns (uint256);

    function baseInterestRateBps() external view returns (uint256);

    function riskPremiumPerStainBps() external view returns (uint256);

    function addLeverageTier(uint8 min_average_level, uint256 multiplier, uint256 interest_rate_bps) external;

    function updateLeverageTier(uint256 tier_id, uint8 min_average_level, uint256 multiplier, uint256 interest_rate_bps) external;

    function setMinLevelForCredit(uint8 new_min_level) external;

    function setMaxLeverageMultiplier(uint256 new_max_multiplier) external;

    function setBaseInterestRate(uint256 new_rate_bps) external;

    function setRiskPremium(uint256 new_premium_bps) external;

    function transferOwnership(address new_owner) external;

    function onlyOwner() external view;

    function getGroupStats(address[] memory members) external view returns (uint8, uint256);

    function getTierForAverageLevel(uint8 avg_level) external view returns (uint256, uint256);
}
